name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: ghcordeiro
          outputs: |
            ghcordeiro/output/github-contribution-grid-snake.svg
            ghcordeiro/output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando animação da cobrinha"
          add: "output/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
