name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  push:
    branches:
      - main  # Executa sempre que houver commit na main
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: ghcordeiro

      - name: Commit e Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando animação da cobrinha"
          add: "output/github-contribution-grid-snake.svg"
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
